D://crw_data//df.apply\source107\code\pd.DataFrame.apply_where_replace0.py,"TypeError: \'Series\' objects are mutable, thus they cannot be hashed",0D://crw_data//df.apply\source13\code\pd.Series.apply_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//df.apply\source13\code\pd.Series.apply_map_replace1.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//df.apply\source14\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',0D://crw_data//df.apply\source14\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.apply\source14\code\pd.DataFrame.fillna_replace2.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.apply\source14\code\pd.Series.apply_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//df.apply\source17\code\pd.Series.apply_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//df.apply\source20\code\pd.Series.astype_replace0.py,AttributeError: \'datetime64[ns]\' is not a valid function for \'Series\' object,1D://crw_data//df.apply\source23\code\pd.Series.apply_map_replace1.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//df.apply\source25\code\pd.DataFrame.apply_where_replace0.py,"TypeError: \'Series\' objects are mutable, thus they cannot be hashed",0D://crw_data//df.apply\source25\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//df.apply\source25\code\pd.Series.astype_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//df.apply\source25\code\pd.Series.astype_replace2.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//df.apply\source30\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.apply\source30\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.apply\source34\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.apply\source34\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.apply\source34\code\pd.Series.replace_map_replace0.py,"AttributeError: (""\'str\' object has no attribute \'map\'"", \'occurred at index 0\')",1D://crw_data//df.apply\source37\code\pd.Series.apply_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//df.apply\source38\code\pd.Series.apply_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//df.apply\source40\code\pd.Series.apply_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//df.apply\source54\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.apply\source58\code\pd.DataFrame.apply_where_replace0.py,"TypeError: \'Series\' objects are mutable, thus they cannot be hashed",0D://crw_data//df.apply\source60\code\pd.DataFrame.apply_where_replace0.py,"TypeError: \'Series\' objects are mutable, thus they cannot be hashed",0D://crw_data//df.apply\source69\code\pd.Series.astype_replace0.py,AttributeError: \'datetime64[ns]\' is not a valid function for \'Series\' object,1D://crw_data//df.astype\source2\code\np.linalg.norm_replace1.py,AssertionError,0D://crw_data//df.at\source14\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.at\source16\code\pd.Series.replace_map_replace0.py,TypeError: \'tuple\' object is not callable,0D://crw_data//df.at\source21\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//df.at\source23\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//df.at\source26\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//df.at\source9\code\pd.Series.replace_map_replace1.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//df.fillna\source10\code\pd.Series.astype_replace0.py,AttributeError: \'DatetimeIndex\' object has no attribute \'apply\',1D://crw_data//df.fillna\source13\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.fillna\source23\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//df.fillna\source23\code\pd.Series.astype_replace3.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//df.fillna\source23\code\pd.Series.astype_replace4.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//df.fillna\source23\code\pd.Series.astype_replace5.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//df.fillna\source23\code\pd.Series.astype_replace6.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//df.fillna\source3\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.fillna\source32\code\np.transpose_column_stack_replace2.py,AttributeError: \'DataFrame\' object has no attribute \'column_stack\',0D://crw_data//df.fillna\source32\code\np.transpose_column_stack_replace3.py,AttributeError: \'DataFrame\' object has no attribute \'column_stack\',0D://crw_data//df.fillna\source33\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//df.fillna\source41\code\pd.Series.replace_map_replace0.py,TypeError: map() got an unexpected keyword argument \'to_map\',0D://crw_data//df.fillna\source44\code\pd.Series.replace_map_replace1.py,TypeError: map() got an unexpected keyword argument \'inplace\',0D://crw_data//df.fillna\source54\code\pd.Series.iloc_replace0.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.fillna\source54\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.fillna\source54\code\pd.Series.iloc_replace4.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source12\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source12\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source19\code\pd.Series.iloc_replace5.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source19\code\pd.Series.replace_map_replace0.py,TypeError: map() got an unexpected keyword argument \'inplace\',0D://crw_data//df.iloc\source2\code\pd.DataFrame.iloc_replace0.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source2\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source2\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source2\code\pd.Series.iloc_replace5.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source20\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iloc\source21\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iloc\source21\code\pd.DataFrame.iloc_replace1.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iloc\source22\code\pd.DataFrame.iloc_replace0.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source22\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source22\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source22\code\pd.Series.iloc_replace5.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source29\code\pd.Series.iloc_replace0.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source30\code\np.ndarray.sum_count_nonzero_replace0.py,AssertionError,1D://crw_data//df.iloc\source30\code\np.ndarray.sum_einsum_replace0.py,AssertionError,1D://crw_data//df.iloc\source30\code\pd.DataFrame.iloc_replace0.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source30\code\pd.Series.astype_replace0.py,AttributeError: apply not found,0D://crw_data//df.iloc\source31\code\pd.DataFrame.iloc_replace0.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source31\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source31\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.iloc\source33\code\np.ndarray.sum_count_nonzero_replace0.py,AssertionError: occurred at index E\xe6\xb4\xbe,1D://crw_data//df.iloc\source33\code\pd.Series.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iloc\source38\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iloc\source45\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iloc\source46\code\pd.DataFrame.iloc_replace0.py,TypeError: _get_value() missing 1 required positional argument: \'col\',0D://crw_data//df.iloc\source46\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.iloc\source46\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.iloc\source60\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iloc\source70\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iloc\source79\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',0D://crw_data//df.iloc\source79\code\pd.Series.astype_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',0D://crw_data//df.iloc\source87\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.iterrows\source7\code\pd.Series.replace_map_replace0.py,TypeError: \'str\' object is not callable,1D://crw_data//df.join\source10\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.join\source11\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.join\source11\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.join\source59\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.join\source59\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//df.loc\source106\code\pd.Series.astype_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//df.loc\source120\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source120\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source122\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source122\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source136\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source136\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source143\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source143\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source154\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source154\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source162\code\pd.Series.replace_map_replace0.py,TypeError: \'list\' object is not callable,1D://crw_data//df.loc\source254\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source254\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',1D://crw_data//df.loc\source88\code\np.ndarray.sum_count_nonzero_replace0.py,"ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().",1D://crw_data//df.merge\source81\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//df.merge\source88\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//df.replace\source1\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//np.abs\source108\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.abs\source33\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//np.abs\source4\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//np.abs\source67\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.abs\source67\code\np.arange_replace1.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.abs\source67\code\np.arange_replace2.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.abs\source9\code\np.transpose_column_stack_replace0.py,AttributeError: column_stack not found,0D://crw_data//np.abs\source96\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source15\code\pd.DataFrame.iloc_replace0.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.append\source23\code\np.array_fromiter_replace0.py,ValueError: invalid literal for int() with base 10: \'pixel0\',0D://crw_data//np.append\source23\code\np.array_fromiter_replace1.py,ValueError: invalid literal for int() with base 10: \'pixel0\',0D://crw_data//np.append\source30\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//np.append\source31\code\pd.Series.iloc_replace1.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source31\code\pd.Series.iloc_replace2.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source31\code\pd.Series.iloc_replace3.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source31\code\pd.Series.iloc_replace4.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source31\code\pd.Series.iloc_replace5.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source31\code\pd.Series.iloc_replace6.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source31\code\pd.Series.iloc_replace7.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source31\code\pd.Series.iloc_replace8.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.append\source32\code\pd.Series.replace_map_replace0.py,AttributeError: \'numpy.str_\' object has no attribute \'map\',1D://crw_data//np.append\source5\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.float64\' object has no attribute \'apply\',1D://crw_data//np.arange\source120\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.arange\source120\code\pd.Series.replace_map_replace0.py,AttributeError: \'StringMethods\' object has no attribute \'map\',1D://crw_data//np.arange\source13\code\pd.Series.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.arange\source13\code\pd.Series.iloc_replace1.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.arange\source2\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source204\code\np.arange_replace0.py,"b""TypeError: 'numpy.float64' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source215\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.arange\source219\code\np.arange_replace0.py,"b""TypeError: 'numpy.float64' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source219\code\np.arange_replace1.py,"b""TypeError: 'numpy.float64' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source227\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source232\code\pd.Series.astype_replace0.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//np.arange\source235\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.arange\source257\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.arange\source257\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.arange\source281\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.arange\source296\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source296\code\np.arange_replace1.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source296\code\np.arange_replace2.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source296\code\np.arange_replace3.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source302\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source303\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source315\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.arange\source345\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.arange\source35\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source385\code\np.arange_replace0.py,"b""TypeError: 'numpy.float64' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source385\code\np.arange_replace1.py,"b""TypeError: 'numpy.float64' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source404\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source404\code\np.arange_replace1.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source404\code\np.arange_replace2.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source404\code\np.arange_replace3.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source406\code\np.ndarray.sum_count_nonzero_replace0.py,AssertionError,1D://crw_data//np.arange\source409\code\np.ndarray.sum_count_nonzero_replace0.py,AssertionError,1D://crw_data//np.arange\source99\code\np.arange_replace0.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.arange\source99\code\np.arange_replace1.py,"b""TypeError: 'float' object cannot be interpreted as an integer\r\n""",1D://crw_data//np.argmax\source110\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.argmax\source110\code\np.transpose_column_stack_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.argmax\source110\code\np.transpose_column_stack_replace2.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.argmax\source22\code\np.c__nonzero_replace0.py,ValueError: all the input arrays must have same number of dimensions,1D://crw_data//np.argmax\source29\code\np.vstack_concatenate_replace0.py,"ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)",1D://crw_data//np.argmax\source29\code\np.vstack_concatenate_replace1.py,"ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)",1D://crw_data//np.argmax\source76\code\np.array_fromiter_replace0.py,ValueError: could not convert string to float: \'bone_length\',0D://crw_data//np.argmax\source76\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.argmax\source76\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.argmax\source76\code\pd.Series.astype_replace3.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.argsort\source126\code\pd.Series.iloc_replace0.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.argsort\source126\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.argsort\source37\code\np.where_apply_replace0.py,NameError: name \'df\' is not defined,1D://crw_data//np.argsort\source56\code\np.ndarray.sum_count_nonzero_replace0.py,AssertionError,1D://crw_data//np.argsort\source90\code\np.where_map_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'map\',1D://crw_data//np.array\source100\code\np.where_apply_replace0.py,NameError: name \'df\' is not defined,0D://crw_data//np.array\source1007\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source1065\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source1065\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//np.array\source1083\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source1124\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.array\source1124\code\pd.Series.astype_replace0.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//np.array\source1174\code\np.dot_einsum_replace0.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 0,0D://crw_data//np.array\source1215\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source19\code\pd.Series.astype_replace3.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source195\code\pd.Series.replace_map_replace0.py,AttributeError: \'StringMethods\' object has no attribute \'map\',1D://crw_data//np.array\source199\code\pd.Series.astype_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source238\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source247\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//np.array\source249\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//np.array\source259\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source422\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source422\code\np.transpose_column_stack_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source422\code\np.transpose_column_stack_replace3.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source422\code\np.transpose_column_stack_replace4.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source422\code\np.transpose_column_stack_replace5.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source429\code\np.array_fromiter_replace0.py,ValueError: setting an array element with a sequence.,0D://crw_data//np.array\source429\code\np.c__nonzero_replace6.py,ValueError: all the input arrays must have same number of dimensions,0D://crw_data//np.array\source429\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source429\code\np.transpose_column_stack_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source429\code\np.transpose_column_stack_replace2.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source429\code\np.transpose_column_stack_replace3.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source429\code\np.transpose_column_stack_replace4.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source429\code\np.transpose_column_stack_replace5.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source429\code\np.transpose_column_stack_replace6.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',0D://crw_data//np.array\source429\code\np.transpose_column_stack_replace7.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',0D://crw_data//np.array\source474\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//np.array\source608\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source608\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//np.array\source609\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source742\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source888\code\pd.Series.astype_replace0.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//np.array\source891\code\pd.Series.astype_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source891\code\pd.Series.astype_replace2.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source919\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source930\code\pd.Series.astype_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source930\code\pd.Series.astype_replace2.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source939\code\pd.Series.astype_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source960\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//np.array\source961\code\pd.Series.astype_replace1.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source962\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source970\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source977\code\pd.Series.astype_replace3.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source994\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.array\source994\code\pd.Series.astype_replace2.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',0D://crw_data//np.array\source994\code\pd.Series.astype_replace6.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',0D://crw_data//np.array\source998\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.column_stack\source17\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.column_stack\source18\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.column_stack\source21\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.column_stack\source28\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.concatenate\source104\code\pd.Series.astype_replace0.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//np.concatenate\source104\code\pd.Series.astype_replace1.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//np.concatenate\source104\code\pd.Series.astype_replace2.py,AttributeError: \'category\' is not a valid function for \'Series\' object,1D://crw_data//np.concatenate\source113\code\np.vstack_concatenate_replace0.py,ValueError: zero-dimensional arrays cannot be concatenated,1D://crw_data//np.concatenate\source113\code\np.vstack_concatenate_replace1.py,ValueError: zero-dimensional arrays cannot be concatenated,1D://crw_data//np.concatenate\source114\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.concatenate\source116\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.concatenate\source133\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source196\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//np.concatenate\source215\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',0D://crw_data//np.concatenate\source235\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source235\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source235\code\pd.DataFrame.fillna_replace2.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source244\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source244\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source244\code\pd.DataFrame.fillna_replace2.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source32\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.concatenate\source44\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.concatenate\source44\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.concatenate\source44\code\pd.Series.iloc_replace5.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.concatenate\source84\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source84\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source96\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source96\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.concatenate\source96\code\pd.DataFrame.fillna_replace2.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.count_nonzero\source6\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.count_nonzero\source6\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.count_nonzero\source6\code\pd.DataFrame.fillna_replace2.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.count_nonzero\source6\code\pd.DataFrame.fillna_replace3.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.count_nonzero\source6\code\pd.DataFrame.fillna_replace4.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.count_nonzero\source6\code\pd.DataFrame.fillna_replace5.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//np.full\source28\code\pd.Series.astype_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'int\',0D://crw_data//np.hstack\source16\code\pd.DataFrame.apply_where_replace0.py,TypeError: cannot convert the series to <class \'int\'>,0D://crw_data//np.hstack\source31\code\pd.Series.astype_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'apply\',1D://crw_data//np.hstack\source53\code\np.vstack_concatenate_replace0.py,"ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)",0D://crw_data//np.sum\source172\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//np.sum\source238\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//np.vectorize\source5\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',0D://crw_data//np.where\source21\code\np.transpose_column_stack_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'column_stack\',1D://crw_data//np.zeros\source113\code\pd.Series.replace_map_replace0.py,AttributeError: \'bytes\' object has no attribute \'map\',1D://crw_data//np.zeros\source137\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source137\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source137\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//np.zeros\source14\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source14\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//np.zeros\source141\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source141\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source142\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source142\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source160\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source18\code\pd.Series.replace_map_replace0.py,AttributeError: \'bytes\' object has no attribute \'map\',1D://crw_data//np.zeros\source183\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source183\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source2\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source2\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source305\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source313\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source313\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source340\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source344\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source344\code\pd.Series.map_replace_replace1.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source353\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source366\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int32)\' and \'str\',0D://crw_data//np.zeros\source520\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',0D://crw_data//np.zeros\source73\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source73\code\pd.Series.iloc_replace3.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//np.zeros\source87\code\pd.Series.iloc_replace1.py,ValueError: Invalid call for scalar access (getting)!,0D://crw_data//pd.concat\source1002\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//pd.concat\source1054\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//pd.concat\source1118\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//pd.concat\source114\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//pd.concat\source195\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.concat\source263\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//pd.concat\source401\code\pd.Series.str_replace0.py,TypeError: \'float\' object is not subscriptable,2D://crw_data//pd.concat\source672\code\np.transpose_column_stack_replace0.py,AttributeError: \'numpy.ndarray\' object has no attribute \'column_stack\',1D://crw_data//pd.concat\source707\code\pd.Series.map_replace_replace0.py,TypeError: Cannot compare types \'ndarray(dtype=int64)\' and \'int\',0D://crw_data//pd.read_csv\source1025\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//pd.read_csv\source1025\code\pd.DataFrame.fillna_replace1.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//pd.read_csv\source1025\code\pd.DataFrame.fillna_replace2.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//pd.read_csv\source1230\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source1268\code\pd.Series.str_replace0.py,TypeError: \'float\' object is not subscriptable,2D://crw_data//pd.read_csv\source1587\code\pd.Series.str_replace0.py,TypeError: \'int\' object is not subscriptable,2D://crw_data//pd.read_csv\source1587\code\pd.Series.str_replace1.py,TypeError: \'int\' object is not subscriptable,2D://crw_data//pd.read_csv\source1587\code\pd.Series.str_replace2.py,TypeError: \'int\' object is not subscriptable,2D://crw_data//pd.read_csv\source1761\code\np.transpose_column_stack_replace0.py,AttributeError: \'Series\' object has no attribute \'column_stack\',1D://crw_data//pd.read_csv\source183\code\pd.Series.map_replace_replace0.py,NameError: name \'replace\' is not defined,1D://crw_data//pd.read_csv\source2251\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//pd.read_csv\source2525\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source2528\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source2528\code\pd.DataFrame.iloc_replace1.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source2629\code\pd.Series.replace_map_replace0.py,TypeError: \'str\' object is not callable,0D://crw_data//pd.read_csv\source2771\code\pd.Series.replace_map_replace0.py,TypeError: \'int\' object is not callable,1D://crw_data//pd.read_csv\source2829\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source2829\code\pd.DataFrame.iloc_replace1.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source283\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source3006\code\pd.DataFrame.iloc_replace0.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source3006\code\pd.DataFrame.iloc_replace1.py,ValueError: iAt based indexing can only have integer indexers,0D://crw_data//pd.read_csv\source3198\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//pd.read_csv\source3653\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//pd.read_csv\source3772\code\pd.Series.replace_map_replace0.py,AttributeError: \'str\' object has no attribute \'map\',1D://crw_data//pd.read_csv\source40\code\pd.Series.replace_map_replace0.py,AttributeError: \'DataFrame\' object has no attribute \'map\',1D://crw_data//pd.read_csv\source695\code\pd.DataFrame.fillna_replace0.py,AttributeError: \'Series\' object has no attribute \'applymap\',1D://crw_data//pd.read_csv\source695\code\pd.Series.replace_map_replace0.py,TypeError: \'str\' object is not callable,1D://crw_data//df.apply\source42\code\np.sum_einsum_replace0.py,AssertionError: occurred at index 0,2D://crw_data//df.astype\source2\code\np.ndarray.sum_einsum_replace0.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 0,2D://crw_data//df.astype\source2\code\np.sum_einsum_replace1.py,"ValueError: operand has more dimensions than subscripts given in einstein sum, but no \'...\' ellipsis provided to broadcast the extra dimensions.",0D://crw_data//df.fillna\source20\code\np.ndarray.sum_einsum_replace0.py,"ValueError: operand has more dimensions than subscripts given in einstein sum, but no \'...\' ellipsis provided to broadcast the extra dimensions.",2D://crw_data//df.fillna\source32\code\np.dot_einsum_replace1.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 1,0D://crw_data//df.fillna\source33\code\np.ndarray.sum_einsum_replace0.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 0,2D://crw_data//df.fillna\source44\code\np.ndarray.sum_einsum_replace0.py,"ValueError: operand has more dimensions than subscripts given in einstein sum, but no \'...\' ellipsis provided to broadcast the extra dimensions.",2D://crw_data//df.iloc\source20\code\np.ndarray.sum_einsum_replace0.py,"ValueError: operand has more dimensions than subscripts given in einstein sum, but no \'...\' ellipsis provided to broadcast the extra dimensions.",1D://crw_data//df.iloc\source62\code\np.sum_einsum_replace0.py,AssertionError,1D://crw_data//df.iloc\source65\code\np.ndarray.sum_einsum_replace0.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 0,2D://crw_data//df.loc\source88\code\np.ndarray.sum_einsum_replace0.py,"ValueError: operand has more dimensions than subscripts given in einstein sum, but no \'...\' ellipsis provided to broadcast the extra dimensions.",1D://crw_data//np.abs\source105\code\np.hstack_concatenate_replace0.py,AssertionError,0D://crw_data//np.abs\source105\code\np.hstack_replace0.py,AssertionError,0D://crw_data//np.abs\source3\code\np.hstack_concatenate_replace0.py,AssertionError,0D://crw_data//np.abs\source3\code\np.hstack_replace0.py,AssertionError,2D://crw_data//np.append\source47\code\np.ndarray.sum_einsum_replace0.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 0,2D://crw_data//np.arange\source253\code\np.ndarray.sum_einsum_replace0.py,AssertionError,2
D://crw_data//np.arange\source311\code\np.ndarray.sum_einsum_replace0.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 0,0
D://crw_data//np.array\source60\code\pd.Series.astype_replace0.py,AssertionError,2
D://crw_data//np.concatenate\source113\code\np.dot_einsum_replace2.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 0,0
D://crw_data//np.concatenate\source113\code\np.dot_einsum_replace3.py,ValueError: einstein sum subscripts string contains too many subscripts for operand 0,0
D://crw_data//np.linalg.norm\source4\code\np.linalg.norm_replace0.py,TypeError: \'axis\' is an invalid keyword to ufunc \'square\',1
D://crw_data//pd.read_csv\source1522\code\pd.Series.map_replace_replace0.py,NameError: name \'replace\' is not defined,1
D://crw_data//pd.read_csv\source1761\code\np.ndarray.dot_tensordot_replace3.py,AssertionError,1
